name: LootChest
main: fr.black_eyes.lootchest.Main
version: 2.4.2
author: Black_Eyes
api-version: 1.13
softdepend: [MultiWorld, Multiverse-Core, FabledSkyBlock, MultiverseCore, GriefPrevention, Residence, WorldGuard, Factions, FactionsX, Towny]
description: >
             Plugin for Regenerating Chests
commands:
  lootchest:
    description: Main Command
    aliases: lc