name: LootChest
main: fr.black_eyes.lootchest.Main
version: 2.3.8
api-version: 1.13
depend: [ProtocolLib]
softdepend: [MultiWorld, Multiverse-Core, FabledSkyBlock, MultiverseCore]
description: >
             Plugin for Regenerating Chests
commands:
  lootchest:
    description: Main Command
    aliases: lc